# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Note app distribute"
  lane :distribute do
      # build_android_app is a built-in fastlane action.
      firebase_app_distribution(
        app: "1:227273604675:android:72d212e446bf368644def6",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        firebase_cli_token: "1//0eddHy3cWAxoPCgYIARAAGA4SNwF-L9IrDB825Sb9UzDSYC0XZ8Yyy2zsw71FonnG5MhdcJcyIBof28GlWsRT0bcPJu_s2fMhcHk",
        groups: "testers"
      )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

end
