# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build app and deploy to distribution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Install Flutter"
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b 3.19.5 "$GITHUB_WORKSPACE/_flutter"

      - name: "Set enviroment variable"
        run: echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: "Set up JAVA 1.8"
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 1.8

      - run: flutter pub get
      - name: build apk
        run: flutter build apk

#      - name: "Deploy to distribution"
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
#        with:
#          appId:
#          serviceCredentialsFile:
#          serviceCredentialsFileContent:
#          file:


